### ISSUE TITLE
bento terminates if prlctl is not available.

### ISSUE THREAD

**Issue by karcaw** [cheeseplus/bento-ya#4]
if you dont have parallels installed after the first build it exits as such:
```
>>> No such file or directory - prlctl
```

**Comment by cheeseplus** [comment]
I see you created a fork, any chance of a PR with the fix? If not we'll get to it

**Comment by karcaw** [comment]
is PR#5 not sufficient?

Evan

**Comment by cheeseplus** [comment]
I was on my phone and the interface didn't make it clear - merged #5
